---
title: "Project - Coursera Getting and Cleaning Data"
output: 
  html_document:
    keep_md: yes
---

---

## Summary
This repository contains R scripts, files and data files related to the project of the Coursera course **Getting and Cleaning Data**. 

Repository files summary :

1. `README.md` : this file. Contains a short overview.
2. `run_analysis.R` : all R scripts built to fulfill project requests.
3. `CodeBook.md` : describes the variables, the data, and any transformations or work performed to clean up the [original data](<https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip>).
4. `finalTidyDataSet.csv` : final tidy data set created according project request.

---

## Running the script
Required steps to run the `run_analysis.R`.

1. Fork this Github repository to your own account.
2. Clone to your local computer.
3. Change dir to the directory with all files listed above.
4. Download and unzip the original dataset `getdata-projectfiles-UCI HAR Dataset.zip`
     + <https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip>. 
     + Files explaining the original dataset (including variables and the data) can be found inside this zip file.
     + [The data linked to from the course website represent data collected from the accelerometers from the Samsung Galaxy S smartphone](http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones)
5. with R Studio or R, run `run_analysis.R`.

---


